export const CHANGE_TEXT_FILTER = 'CHANGE_TEXT_FILTER';
export const CHANGE_COMPLETED_FILTER = 'CHANGE_COMPLETED_FILTER';

export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';